### ISSUE TITLE
How could I run the project?

### ISSUE THREAD

**Issue by kevinding0218** [bytefish/SignalRSample#3]
Hello, thank you for the very detailed tutorial about SignalR with real-time chart display! I was trying to load and run the project, but having trouble to see the chart page by going through http://localhost:5000, the startup project was set up with SignalRSample.Web and I am also kind of confusing that, if I should start the SignalRSample.ConsoleApp manually and separately but how could I start it, I didn't find the .exe file anywhere in the ConsoleApp project anyway? I set a break-point in the Main() function of SignalRSample.ConsoleApp but it seems not hit there...
BTW, is there any way other than the Console App to trigger the SignalR Hub like using WebMethod in asp.net webform or web api in asp.net core?

Best,

**Comment by bytefish** [comment]
Set the Web project as Start project. Then in Visual Studio you can right click the Console project, look for "Debug" and select "Start New Instance". You can find a detailed explanation here: https://docs.microsoft.com/en-us/visualstudio/debugger/debug-multiple-processes?view=vs-2017.

**Comment by bytefish** [comment]
Although I closed the issue, feel free to ask. 😅
